/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AffiliateRouteImport } from './routes/affiliate'
import { Route as AvailableChannelsRouteImport } from './routes/available-channels'
import { Route as BatchImageRouteImport } from './routes/batch-image'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EmailVerifyRouteImport } from './routes/email-verify'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HomeRouteImport } from './routes/home'
import { Route as KeyUsageRouteImport } from './routes/key-usage'
import { Route as KeysRouteImport } from './routes/keys'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ModelPlazaRouteImport } from './routes/model-plaza'
import { Route as MonitorRouteImport } from './routes/monitor'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PurchaseRouteImport } from './routes/purchase'
import { Route as RedeemRouteImport } from './routes/redeem'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as AdminAccountsRouteImport } from './routes/admin/accounts'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin/announcements'
import { Route as AdminAuditLogsRouteImport } from './routes/admin/audit-logs'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminGroupsRouteImport } from './routes/admin/groups'
import { Route as AdminOpsRouteImport } from './routes/admin/ops'
import { Route as AdminPromoCodesRouteImport } from './routes/admin/promo-codes'
import { Route as AdminPromptAuditRouteImport } from './routes/admin/prompt-audit'
import { Route as AdminProxiesRouteImport } from './routes/admin/proxies'
import { Route as AdminRedeemRouteImport } from './routes/admin/redeem'
import { Route as AdminRiskControlRouteImport } from './routes/admin/risk-control'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin/subscriptions'
import { Route as AdminUsageRouteImport } from './routes/admin/usage'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as CustomIdRouteImport } from './routes/custom.$id'
import { Route as DevUiRouteImport } from './routes/dev/ui'
import { Route as DocsBatchImageRouteImport } from './routes/docs/batch-image'
import { Route as LegalDocumentIdRouteImport } from './routes/legal/$documentId'
import { Route as PaymentAirwallexRouteImport } from './routes/payment/airwallex'
import { Route as PaymentQrcodeRouteImport } from './routes/payment/qrcode'
import { Route as PaymentResultRouteImport } from './routes/payment/result'
import { Route as PaymentStripeRouteImport } from './routes/payment/stripe'
import { Route as PaymentStripePopupRouteImport } from './routes/payment/stripe-popup'
import { Route as AdminAffiliatesInvitesRouteImport } from './routes/admin/affiliates/invites'
import { Route as AdminAffiliatesRebatesRouteImport } from './routes/admin/affiliates/rebates'
import { Route as AdminAffiliatesTransfersRouteImport } from './routes/admin/affiliates/transfers'
import { Route as AdminChannelsMonitorRouteImport } from './routes/admin/channels/monitor'
import { Route as AdminChannelsPricingRouteImport } from './routes/admin/channels/pricing'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as AdminOrdersDashboardRouteImport } from './routes/admin/orders/dashboard'
import { Route as AdminOrdersPlansRouteImport } from './routes/admin/orders/plans'
import { Route as AuthDingtalkCallbackRouteImport } from './routes/auth/dingtalk/callback'
import { Route as AuthDingtalkEmailCompletionRouteImport } from './routes/auth/dingtalk/email-completion'
import { Route as AuthLinuxdoCallbackRouteImport } from './routes/auth/linuxdo/callback'
import { Route as AuthOidcCallbackRouteImport } from './routes/auth/oidc/callback'
import { Route as AuthWechatCallbackRouteImport } from './routes/auth/wechat/callback'
import { Route as AuthWechatPaymentCallbackRouteImport } from './routes/auth/wechat/payment/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateRoute = AffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailableChannelsRoute = AvailableChannelsRouteImport.update({
  id: '/available-channels',
  path: '/available-channels',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchImageRoute = BatchImageRouteImport.update({
  id: '/batch-image',
  path: '/batch-image',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailVerifyRoute = EmailVerifyRouteImport.update({
  id: '/email-verify',
  path: '/email-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const KeyUsageRoute = KeyUsageRouteImport.update({
  id: '/key-usage',
  path: '/key-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const KeysRoute = KeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelPlazaRoute = ModelPlazaRouteImport.update({
  id: '/model-plaza',
  path: '/model-plaza',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorRoute = MonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRoute = PurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const RedeemRoute = RedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountsRoute = AdminAccountsRouteImport.update({
  id: '/admin/accounts',
  path: '/admin/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/admin/announcements',
  path: '/admin/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGroupsRoute = AdminGroupsRouteImport.update({
  id: '/admin/groups',
  path: '/admin/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOpsRoute = AdminOpsRouteImport.update({
  id: '/admin/ops',
  path: '/admin/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPromoCodesRoute = AdminPromoCodesRouteImport.update({
  id: '/admin/promo-codes',
  path: '/admin/promo-codes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPromptAuditRoute = AdminPromptAuditRouteImport.update({
  id: '/admin/prompt-audit',
  path: '/admin/prompt-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProxiesRoute = AdminProxiesRouteImport.update({
  id: '/admin/proxies',
  path: '/admin/proxies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRedeemRoute = AdminRedeemRouteImport.update({
  id: '/admin/redeem',
  path: '/admin/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRiskControlRoute = AdminRiskControlRouteImport.update({
  id: '/admin/risk-control',
  path: '/admin/risk-control',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/admin/subscriptions',
  path: '/admin/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsageRoute = AdminUsageRouteImport.update({
  id: '/admin/usage',
  path: '/admin/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomIdRoute = CustomIdRouteImport.update({
  id: '/custom/$id',
  path: '/custom/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DevUiRoute = DevUiRouteImport.update({
  id: '/dev/ui',
  path: '/dev/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsBatchImageRoute = DocsBatchImageRouteImport.update({
  id: '/docs/batch-image',
  path: '/docs/batch-image',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDocumentIdRoute = LegalDocumentIdRouteImport.update({
  id: '/legal/$documentId',
  path: '/legal/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentAirwallexRoute = PaymentAirwallexRouteImport.update({
  id: '/payment/airwallex',
  path: '/payment/airwallex',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentQrcodeRoute = PaymentQrcodeRouteImport.update({
  id: '/payment/qrcode',
  path: '/payment/qrcode',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentResultRoute = PaymentResultRouteImport.update({
  id: '/payment/result',
  path: '/payment/result',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentStripeRoute = PaymentStripeRouteImport.update({
  id: '/payment/stripe',
  path: '/payment/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentStripePopupRoute = PaymentStripePopupRouteImport.update({
  id: '/payment/stripe-popup',
  path: '/payment/stripe-popup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAffiliatesInvitesRoute = AdminAffiliatesInvitesRouteImport.update({
  id: '/admin/affiliates/invites',
  path: '/admin/affiliates/invites',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAffiliatesRebatesRoute = AdminAffiliatesRebatesRouteImport.update({
  id: '/admin/affiliates/rebates',
  path: '/admin/affiliates/rebates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAffiliatesTransfersRoute =
  AdminAffiliatesTransfersRouteImport.update({
    id: '/admin/affiliates/transfers',
    path: '/admin/affiliates/transfers',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminChannelsMonitorRoute = AdminChannelsMonitorRouteImport.update({
  id: '/admin/channels/monitor',
  path: '/admin/channels/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChannelsPricingRoute = AdminChannelsPricingRouteImport.update({
  id: '/admin/channels/pricing',
  path: '/admin/channels/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/admin/orders/',
  path: '/admin/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersDashboardRoute = AdminOrdersDashboardRouteImport.update({
  id: '/admin/orders/dashboard',
  path: '/admin/orders/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersPlansRoute = AdminOrdersPlansRouteImport.update({
  id: '/admin/orders/plans',
  path: '/admin/orders/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDingtalkCallbackRoute = AuthDingtalkCallbackRouteImport.update({
  id: '/auth/dingtalk/callback',
  path: '/auth/dingtalk/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDingtalkEmailCompletionRoute =
  AuthDingtalkEmailCompletionRouteImport.update({
    id: '/auth/dingtalk/email-completion',
    path: '/auth/dingtalk/email-completion',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthLinuxdoCallbackRoute = AuthLinuxdoCallbackRouteImport.update({
  id: '/auth/linuxdo/callback',
  path: '/auth/linuxdo/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOidcCallbackRoute = AuthOidcCallbackRouteImport.update({
  id: '/auth/oidc/callback',
  path: '/auth/oidc/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthWechatCallbackRoute = AuthWechatCallbackRouteImport.update({
  id: '/auth/wechat/callback',
  path: '/auth/wechat/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthWechatPaymentCallbackRoute =
  AuthWechatPaymentCallbackRouteImport.update({
    id: '/auth/wechat/payment/callback',
    path: '/auth/wechat/payment/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/affiliate': typeof AffiliateRoute
  '/available-channels': typeof AvailableChannelsRoute
  '/batch-image': typeof BatchImageRoute
  '/dashboard': typeof DashboardRoute
  '/email-verify': typeof EmailVerifyRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/key-usage': typeof KeyUsageRoute
  '/keys': typeof KeysRoute
  '/login': typeof LoginRoute
  '/model-plaza': typeof ModelPlazaRoute
  '/monitor': typeof MonitorRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/purchase': typeof PurchaseRoute
  '/redeem': typeof RedeemRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/usage': typeof UsageRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/ops': typeof AdminOpsRoute
  '/admin/promo-codes': typeof AdminPromoCodesRoute
  '/admin/prompt-audit': typeof AdminPromptAuditRoute
  '/admin/proxies': typeof AdminProxiesRoute
  '/admin/redeem': typeof AdminRedeemRoute
  '/admin/risk-control': typeof AdminRiskControlRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/usage': typeof AdminUsageRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/custom/$id': typeof CustomIdRoute
  '/dev/ui': typeof DevUiRoute
  '/docs/batch-image': typeof DocsBatchImageRoute
  '/legal/$documentId': typeof LegalDocumentIdRoute
  '/payment/airwallex': typeof PaymentAirwallexRoute
  '/payment/qrcode': typeof PaymentQrcodeRoute
  '/payment/result': typeof PaymentResultRoute
  '/payment/stripe': typeof PaymentStripeRoute
  '/payment/stripe-popup': typeof PaymentStripePopupRoute
  '/admin/affiliates/invites': typeof AdminAffiliatesInvitesRoute
  '/admin/affiliates/rebates': typeof AdminAffiliatesRebatesRoute
  '/admin/affiliates/transfers': typeof AdminAffiliatesTransfersRoute
  '/admin/channels/monitor': typeof AdminChannelsMonitorRoute
  '/admin/channels/pricing': typeof AdminChannelsPricingRoute
  '/admin/orders/dashboard': typeof AdminOrdersDashboardRoute
  '/admin/orders/plans': typeof AdminOrdersPlansRoute
  '/auth/dingtalk/callback': typeof AuthDingtalkCallbackRoute
  '/auth/dingtalk/email-completion': typeof AuthDingtalkEmailCompletionRoute
  '/auth/linuxdo/callback': typeof AuthLinuxdoCallbackRoute
  '/auth/oidc/callback': typeof AuthOidcCallbackRoute
  '/auth/wechat/callback': typeof AuthWechatCallbackRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/auth/wechat/payment/callback': typeof AuthWechatPaymentCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/affiliate': typeof AffiliateRoute
  '/available-channels': typeof AvailableChannelsRoute
  '/batch-image': typeof BatchImageRoute
  '/dashboard': typeof DashboardRoute
  '/email-verify': typeof EmailVerifyRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/key-usage': typeof KeyUsageRoute
  '/keys': typeof KeysRoute
  '/login': typeof LoginRoute
  '/model-plaza': typeof ModelPlazaRoute
  '/monitor': typeof MonitorRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/purchase': typeof PurchaseRoute
  '/redeem': typeof RedeemRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/usage': typeof UsageRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/ops': typeof AdminOpsRoute
  '/admin/promo-codes': typeof AdminPromoCodesRoute
  '/admin/prompt-audit': typeof AdminPromptAuditRoute
  '/admin/proxies': typeof AdminProxiesRoute
  '/admin/redeem': typeof AdminRedeemRoute
  '/admin/risk-control': typeof AdminRiskControlRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/usage': typeof AdminUsageRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/custom/$id': typeof CustomIdRoute
  '/dev/ui': typeof DevUiRoute
  '/docs/batch-image': typeof DocsBatchImageRoute
  '/legal/$documentId': typeof LegalDocumentIdRoute
  '/payment/airwallex': typeof PaymentAirwallexRoute
  '/payment/qrcode': typeof PaymentQrcodeRoute
  '/payment/result': typeof PaymentResultRoute
  '/payment/stripe': typeof PaymentStripeRoute
  '/payment/stripe-popup': typeof PaymentStripePopupRoute
  '/admin/affiliates/invites': typeof AdminAffiliatesInvitesRoute
  '/admin/affiliates/rebates': typeof AdminAffiliatesRebatesRoute
  '/admin/affiliates/transfers': typeof AdminAffiliatesTransfersRoute
  '/admin/channels/monitor': typeof AdminChannelsMonitorRoute
  '/admin/channels/pricing': typeof AdminChannelsPricingRoute
  '/admin/orders/dashboard': typeof AdminOrdersDashboardRoute
  '/admin/orders/plans': typeof AdminOrdersPlansRoute
  '/auth/dingtalk/callback': typeof AuthDingtalkCallbackRoute
  '/auth/dingtalk/email-completion': typeof AuthDingtalkEmailCompletionRoute
  '/auth/linuxdo/callback': typeof AuthLinuxdoCallbackRoute
  '/auth/oidc/callback': typeof AuthOidcCallbackRoute
  '/auth/wechat/callback': typeof AuthWechatCallbackRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/auth/wechat/payment/callback': typeof AuthWechatPaymentCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/affiliate': typeof AffiliateRoute
  '/available-channels': typeof AvailableChannelsRoute
  '/batch-image': typeof BatchImageRoute
  '/dashboard': typeof DashboardRoute
  '/email-verify': typeof EmailVerifyRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/key-usage': typeof KeyUsageRoute
  '/keys': typeof KeysRoute
  '/login': typeof LoginRoute
  '/model-plaza': typeof ModelPlazaRoute
  '/monitor': typeof MonitorRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/purchase': typeof PurchaseRoute
  '/redeem': typeof RedeemRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/usage': typeof UsageRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/ops': typeof AdminOpsRoute
  '/admin/promo-codes': typeof AdminPromoCodesRoute
  '/admin/prompt-audit': typeof AdminPromptAuditRoute
  '/admin/proxies': typeof AdminProxiesRoute
  '/admin/redeem': typeof AdminRedeemRoute
  '/admin/risk-control': typeof AdminRiskControlRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/usage': typeof AdminUsageRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/custom/$id': typeof CustomIdRoute
  '/dev/ui': typeof DevUiRoute
  '/docs/batch-image': typeof DocsBatchImageRoute
  '/legal/$documentId': typeof LegalDocumentIdRoute
  '/payment/airwallex': typeof PaymentAirwallexRoute
  '/payment/qrcode': typeof PaymentQrcodeRoute
  '/payment/result': typeof PaymentResultRoute
  '/payment/stripe': typeof PaymentStripeRoute
  '/payment/stripe-popup': typeof PaymentStripePopupRoute
  '/admin/affiliates/invites': typeof AdminAffiliatesInvitesRoute
  '/admin/affiliates/rebates': typeof AdminAffiliatesRebatesRoute
  '/admin/affiliates/transfers': typeof AdminAffiliatesTransfersRoute
  '/admin/channels/monitor': typeof AdminChannelsMonitorRoute
  '/admin/channels/pricing': typeof AdminChannelsPricingRoute
  '/admin/orders/dashboard': typeof AdminOrdersDashboardRoute
  '/admin/orders/plans': typeof AdminOrdersPlansRoute
  '/auth/dingtalk/callback': typeof AuthDingtalkCallbackRoute
  '/auth/dingtalk/email-completion': typeof AuthDingtalkEmailCompletionRoute
  '/auth/linuxdo/callback': typeof AuthLinuxdoCallbackRoute
  '/auth/oidc/callback': typeof AuthOidcCallbackRoute
  '/auth/wechat/callback': typeof AuthWechatCallbackRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/auth/wechat/payment/callback': typeof AuthWechatPaymentCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/affiliate'
    | '/available-channels'
    | '/batch-image'
    | '/dashboard'
    | '/email-verify'
    | '/forgot-password'
    | '/home'
    | '/key-usage'
    | '/keys'
    | '/login'
    | '/model-plaza'
    | '/monitor'
    | '/orders'
    | '/profile'
    | '/purchase'
    | '/redeem'
    | '/register'
    | '/reset-password'
    | '/subscriptions'
    | '/usage'
    | '/admin/accounts'
    | '/admin/announcements'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/groups'
    | '/admin/ops'
    | '/admin/promo-codes'
    | '/admin/prompt-audit'
    | '/admin/proxies'
    | '/admin/redeem'
    | '/admin/risk-control'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/usage'
    | '/admin/users'
    | '/auth/callback'
    | '/custom/$id'
    | '/dev/ui'
    | '/docs/batch-image'
    | '/legal/$documentId'
    | '/payment/airwallex'
    | '/payment/qrcode'
    | '/payment/result'
    | '/payment/stripe'
    | '/payment/stripe-popup'
    | '/admin/affiliates/invites'
    | '/admin/affiliates/rebates'
    | '/admin/affiliates/transfers'
    | '/admin/channels/monitor'
    | '/admin/channels/pricing'
    | '/admin/orders/dashboard'
    | '/admin/orders/plans'
    | '/auth/dingtalk/callback'
    | '/auth/dingtalk/email-completion'
    | '/auth/linuxdo/callback'
    | '/auth/oidc/callback'
    | '/auth/wechat/callback'
    | '/admin/orders/'
    | '/auth/wechat/payment/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/affiliate'
    | '/available-channels'
    | '/batch-image'
    | '/dashboard'
    | '/email-verify'
    | '/forgot-password'
    | '/home'
    | '/key-usage'
    | '/keys'
    | '/login'
    | '/model-plaza'
    | '/monitor'
    | '/orders'
    | '/profile'
    | '/purchase'
    | '/redeem'
    | '/register'
    | '/reset-password'
    | '/subscriptions'
    | '/usage'
    | '/admin/accounts'
    | '/admin/announcements'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/groups'
    | '/admin/ops'
    | '/admin/promo-codes'
    | '/admin/prompt-audit'
    | '/admin/proxies'
    | '/admin/redeem'
    | '/admin/risk-control'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/usage'
    | '/admin/users'
    | '/auth/callback'
    | '/custom/$id'
    | '/dev/ui'
    | '/docs/batch-image'
    | '/legal/$documentId'
    | '/payment/airwallex'
    | '/payment/qrcode'
    | '/payment/result'
    | '/payment/stripe'
    | '/payment/stripe-popup'
    | '/admin/affiliates/invites'
    | '/admin/affiliates/rebates'
    | '/admin/affiliates/transfers'
    | '/admin/channels/monitor'
    | '/admin/channels/pricing'
    | '/admin/orders/dashboard'
    | '/admin/orders/plans'
    | '/auth/dingtalk/callback'
    | '/auth/dingtalk/email-completion'
    | '/auth/linuxdo/callback'
    | '/auth/oidc/callback'
    | '/auth/wechat/callback'
    | '/admin/orders'
    | '/auth/wechat/payment/callback'
  id:
    | '__root__'
    | '/'
    | '/affiliate'
    | '/available-channels'
    | '/batch-image'
    | '/dashboard'
    | '/email-verify'
    | '/forgot-password'
    | '/home'
    | '/key-usage'
    | '/keys'
    | '/login'
    | '/model-plaza'
    | '/monitor'
    | '/orders'
    | '/profile'
    | '/purchase'
    | '/redeem'
    | '/register'
    | '/reset-password'
    | '/subscriptions'
    | '/usage'
    | '/admin/accounts'
    | '/admin/announcements'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/groups'
    | '/admin/ops'
    | '/admin/promo-codes'
    | '/admin/prompt-audit'
    | '/admin/proxies'
    | '/admin/redeem'
    | '/admin/risk-control'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/usage'
    | '/admin/users'
    | '/auth/callback'
    | '/custom/$id'
    | '/dev/ui'
    | '/docs/batch-image'
    | '/legal/$documentId'
    | '/payment/airwallex'
    | '/payment/qrcode'
    | '/payment/result'
    | '/payment/stripe'
    | '/payment/stripe-popup'
    | '/admin/affiliates/invites'
    | '/admin/affiliates/rebates'
    | '/admin/affiliates/transfers'
    | '/admin/channels/monitor'
    | '/admin/channels/pricing'
    | '/admin/orders/dashboard'
    | '/admin/orders/plans'
    | '/auth/dingtalk/callback'
    | '/auth/dingtalk/email-completion'
    | '/auth/linuxdo/callback'
    | '/auth/oidc/callback'
    | '/auth/wechat/callback'
    | '/admin/orders/'
    | '/auth/wechat/payment/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AffiliateRoute: typeof AffiliateRoute
  AvailableChannelsRoute: typeof AvailableChannelsRoute
  BatchImageRoute: typeof BatchImageRoute
  DashboardRoute: typeof DashboardRoute
  EmailVerifyRoute: typeof EmailVerifyRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HomeRoute: typeof HomeRoute
  KeyUsageRoute: typeof KeyUsageRoute
  KeysRoute: typeof KeysRoute
  LoginRoute: typeof LoginRoute
  ModelPlazaRoute: typeof ModelPlazaRoute
  MonitorRoute: typeof MonitorRoute
  OrdersRoute: typeof OrdersRoute
  ProfileRoute: typeof ProfileRoute
  PurchaseRoute: typeof PurchaseRoute
  RedeemRoute: typeof RedeemRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  UsageRoute: typeof UsageRoute
  AdminAccountsRoute: typeof AdminAccountsRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminGroupsRoute: typeof AdminGroupsRoute
  AdminOpsRoute: typeof AdminOpsRoute
  AdminPromoCodesRoute: typeof AdminPromoCodesRoute
  AdminPromptAuditRoute: typeof AdminPromptAuditRoute
  AdminProxiesRoute: typeof AdminProxiesRoute
  AdminRedeemRoute: typeof AdminRedeemRoute
  AdminRiskControlRoute: typeof AdminRiskControlRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminUsageRoute: typeof AdminUsageRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CustomIdRoute: typeof CustomIdRoute
  DevUiRoute: typeof DevUiRoute
  DocsBatchImageRoute: typeof DocsBatchImageRoute
  LegalDocumentIdRoute: typeof LegalDocumentIdRoute
  PaymentAirwallexRoute: typeof PaymentAirwallexRoute
  PaymentQrcodeRoute: typeof PaymentQrcodeRoute
  PaymentResultRoute: typeof PaymentResultRoute
  PaymentStripeRoute: typeof PaymentStripeRoute
  PaymentStripePopupRoute: typeof PaymentStripePopupRoute
  AdminAffiliatesInvitesRoute: typeof AdminAffiliatesInvitesRoute
  AdminAffiliatesRebatesRoute: typeof AdminAffiliatesRebatesRoute
  AdminAffiliatesTransfersRoute: typeof AdminAffiliatesTransfersRoute
  AdminChannelsMonitorRoute: typeof AdminChannelsMonitorRoute
  AdminChannelsPricingRoute: typeof AdminChannelsPricingRoute
  AdminOrdersDashboardRoute: typeof AdminOrdersDashboardRoute
  AdminOrdersPlansRoute: typeof AdminOrdersPlansRoute
  AuthDingtalkCallbackRoute: typeof AuthDingtalkCallbackRoute
  AuthDingtalkEmailCompletionRoute: typeof AuthDingtalkEmailCompletionRoute
  AuthLinuxdoCallbackRoute: typeof AuthLinuxdoCallbackRoute
  AuthOidcCallbackRoute: typeof AuthOidcCallbackRoute
  AuthWechatCallbackRoute: typeof AuthWechatCallbackRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AuthWechatPaymentCallbackRoute: typeof AuthWechatPaymentCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate': {
      id: '/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/available-channels': {
      id: '/available-channels'
      path: '/available-channels'
      fullPath: '/available-channels'
      preLoaderRoute: typeof AvailableChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch-image': {
      id: '/batch-image'
      path: '/batch-image'
      fullPath: '/batch-image'
      preLoaderRoute: typeof BatchImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-verify': {
      id: '/email-verify'
      path: '/email-verify'
      fullPath: '/email-verify'
      preLoaderRoute: typeof EmailVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/key-usage': {
      id: '/key-usage'
      path: '/key-usage'
      fullPath: '/key-usage'
      preLoaderRoute: typeof KeyUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keys': {
      id: '/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof KeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-plaza': {
      id: '/model-plaza'
      path: '/model-plaza'
      fullPath: '/model-plaza'
      preLoaderRoute: typeof ModelPlazaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor': {
      id: '/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof MonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase': {
      id: '/purchase'
      path: '/purchase'
      fullPath: '/purchase'
      preLoaderRoute: typeof PurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redeem': {
      id: '/redeem'
      path: '/redeem'
      fullPath: '/redeem'
      preLoaderRoute: typeof RedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/accounts': {
      id: '/admin/accounts'
      path: '/admin/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/groups': {
      id: '/admin/groups'
      path: '/admin/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AdminGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ops': {
      id: '/admin/ops'
      path: '/admin/ops'
      fullPath: '/admin/ops'
      preLoaderRoute: typeof AdminOpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/promo-codes': {
      id: '/admin/promo-codes'
      path: '/admin/promo-codes'
      fullPath: '/admin/promo-codes'
      preLoaderRoute: typeof AdminPromoCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/prompt-audit': {
      id: '/admin/prompt-audit'
      path: '/admin/prompt-audit'
      fullPath: '/admin/prompt-audit'
      preLoaderRoute: typeof AdminPromptAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/proxies': {
      id: '/admin/proxies'
      path: '/admin/proxies'
      fullPath: '/admin/proxies'
      preLoaderRoute: typeof AdminProxiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/redeem': {
      id: '/admin/redeem'
      path: '/admin/redeem'
      fullPath: '/admin/redeem'
      preLoaderRoute: typeof AdminRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/risk-control': {
      id: '/admin/risk-control'
      path: '/admin/risk-control'
      fullPath: '/admin/risk-control'
      preLoaderRoute: typeof AdminRiskControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/admin/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usage': {
      id: '/admin/usage'
      path: '/admin/usage'
      fullPath: '/admin/usage'
      preLoaderRoute: typeof AdminUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom/$id': {
      id: '/custom/$id'
      path: '/custom/$id'
      fullPath: '/custom/$id'
      preLoaderRoute: typeof CustomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/ui': {
      id: '/dev/ui'
      path: '/dev/ui'
      fullPath: '/dev/ui'
      preLoaderRoute: typeof DevUiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/batch-image': {
      id: '/docs/batch-image'
      path: '/docs/batch-image'
      fullPath: '/docs/batch-image'
      preLoaderRoute: typeof DocsBatchImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$documentId': {
      id: '/legal/$documentId'
      path: '/legal/$documentId'
      fullPath: '/legal/$documentId'
      preLoaderRoute: typeof LegalDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/airwallex': {
      id: '/payment/airwallex'
      path: '/payment/airwallex'
      fullPath: '/payment/airwallex'
      preLoaderRoute: typeof PaymentAirwallexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/qrcode': {
      id: '/payment/qrcode'
      path: '/payment/qrcode'
      fullPath: '/payment/qrcode'
      preLoaderRoute: typeof PaymentQrcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/result': {
      id: '/payment/result'
      path: '/payment/result'
      fullPath: '/payment/result'
      preLoaderRoute: typeof PaymentResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/stripe': {
      id: '/payment/stripe'
      path: '/payment/stripe'
      fullPath: '/payment/stripe'
      preLoaderRoute: typeof PaymentStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/stripe-popup': {
      id: '/payment/stripe-popup'
      path: '/payment/stripe-popup'
      fullPath: '/payment/stripe-popup'
      preLoaderRoute: typeof PaymentStripePopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/affiliates/invites': {
      id: '/admin/affiliates/invites'
      path: '/admin/affiliates/invites'
      fullPath: '/admin/affiliates/invites'
      preLoaderRoute: typeof AdminAffiliatesInvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/affiliates/rebates': {
      id: '/admin/affiliates/rebates'
      path: '/admin/affiliates/rebates'
      fullPath: '/admin/affiliates/rebates'
      preLoaderRoute: typeof AdminAffiliatesRebatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/affiliates/transfers': {
      id: '/admin/affiliates/transfers'
      path: '/admin/affiliates/transfers'
      fullPath: '/admin/affiliates/transfers'
      preLoaderRoute: typeof AdminAffiliatesTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/channels/monitor': {
      id: '/admin/channels/monitor'
      path: '/admin/channels/monitor'
      fullPath: '/admin/channels/monitor'
      preLoaderRoute: typeof AdminChannelsMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/channels/pricing': {
      id: '/admin/channels/pricing'
      path: '/admin/channels/pricing'
      fullPath: '/admin/channels/pricing'
      preLoaderRoute: typeof AdminChannelsPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/admin/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/dashboard': {
      id: '/admin/orders/dashboard'
      path: '/admin/orders/dashboard'
      fullPath: '/admin/orders/dashboard'
      preLoaderRoute: typeof AdminOrdersDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/plans': {
      id: '/admin/orders/plans'
      path: '/admin/orders/plans'
      fullPath: '/admin/orders/plans'
      preLoaderRoute: typeof AdminOrdersPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/dingtalk/callback': {
      id: '/auth/dingtalk/callback'
      path: '/auth/dingtalk/callback'
      fullPath: '/auth/dingtalk/callback'
      preLoaderRoute: typeof AuthDingtalkCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/dingtalk/email-completion': {
      id: '/auth/dingtalk/email-completion'
      path: '/auth/dingtalk/email-completion'
      fullPath: '/auth/dingtalk/email-completion'
      preLoaderRoute: typeof AuthDingtalkEmailCompletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/linuxdo/callback': {
      id: '/auth/linuxdo/callback'
      path: '/auth/linuxdo/callback'
      fullPath: '/auth/linuxdo/callback'
      preLoaderRoute: typeof AuthLinuxdoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/oidc/callback': {
      id: '/auth/oidc/callback'
      path: '/auth/oidc/callback'
      fullPath: '/auth/oidc/callback'
      preLoaderRoute: typeof AuthOidcCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/wechat/callback': {
      id: '/auth/wechat/callback'
      path: '/auth/wechat/callback'
      fullPath: '/auth/wechat/callback'
      preLoaderRoute: typeof AuthWechatCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/wechat/payment/callback': {
      id: '/auth/wechat/payment/callback'
      path: '/auth/wechat/payment/callback'
      fullPath: '/auth/wechat/payment/callback'
      preLoaderRoute: typeof AuthWechatPaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AffiliateRoute: AffiliateRoute,
  AvailableChannelsRoute: AvailableChannelsRoute,
  BatchImageRoute: BatchImageRoute,
  DashboardRoute: DashboardRoute,
  EmailVerifyRoute: EmailVerifyRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HomeRoute: HomeRoute,
  KeyUsageRoute: KeyUsageRoute,
  KeysRoute: KeysRoute,
  LoginRoute: LoginRoute,
  ModelPlazaRoute: ModelPlazaRoute,
  MonitorRoute: MonitorRoute,
  OrdersRoute: OrdersRoute,
  ProfileRoute: ProfileRoute,
  PurchaseRoute: PurchaseRoute,
  RedeemRoute: RedeemRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  UsageRoute: UsageRoute,
  AdminAccountsRoute: AdminAccountsRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminGroupsRoute: AdminGroupsRoute,
  AdminOpsRoute: AdminOpsRoute,
  AdminPromoCodesRoute: AdminPromoCodesRoute,
  AdminPromptAuditRoute: AdminPromptAuditRoute,
  AdminProxiesRoute: AdminProxiesRoute,
  AdminRedeemRoute: AdminRedeemRoute,
  AdminRiskControlRoute: AdminRiskControlRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminUsageRoute: AdminUsageRoute,
  AdminUsersRoute: AdminUsersRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CustomIdRoute: CustomIdRoute,
  DevUiRoute: DevUiRoute,
  DocsBatchImageRoute: DocsBatchImageRoute,
  LegalDocumentIdRoute: LegalDocumentIdRoute,
  PaymentAirwallexRoute: PaymentAirwallexRoute,
  PaymentQrcodeRoute: PaymentQrcodeRoute,
  PaymentResultRoute: PaymentResultRoute,
  PaymentStripeRoute: PaymentStripeRoute,
  PaymentStripePopupRoute: PaymentStripePopupRoute,
  AdminAffiliatesInvitesRoute: AdminAffiliatesInvitesRoute,
  AdminAffiliatesRebatesRoute: AdminAffiliatesRebatesRoute,
  AdminAffiliatesTransfersRoute: AdminAffiliatesTransfersRoute,
  AdminChannelsMonitorRoute: AdminChannelsMonitorRoute,
  AdminChannelsPricingRoute: AdminChannelsPricingRoute,
  AdminOrdersDashboardRoute: AdminOrdersDashboardRoute,
  AdminOrdersPlansRoute: AdminOrdersPlansRoute,
  AuthDingtalkCallbackRoute: AuthDingtalkCallbackRoute,
  AuthDingtalkEmailCompletionRoute: AuthDingtalkEmailCompletionRoute,
  AuthLinuxdoCallbackRoute: AuthLinuxdoCallbackRoute,
  AuthOidcCallbackRoute: AuthOidcCallbackRoute,
  AuthWechatCallbackRoute: AuthWechatCallbackRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AuthWechatPaymentCallbackRoute: AuthWechatPaymentCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
